version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:3.0
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=WARN"
    ports:
      - "80:80"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"

  app:
    container_name: cash-api
    build:
      context: api
    expose:
      - "8080"
    depends_on:
      - traefik
      - ext_postgresql
    restart: always
    networks:
      - proxy
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ext_postgresql:5432/cash_cockpit
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=verysecret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`cash-cockpit.local`)&&PathPrefix(`/api/`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  ext_postgresql:
    container_name: ext_postgresql_v2
    image: postgres:12
    environment:
      POSTGRES_DB: cash_cockpit
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: verysecret
    expose:
      - "5432"
    restart: always
    networks:
      - app-network
    volumes:
      - postgres:/data/postgres

  angular:
    container_name: angular
    build:
      context: UI
      target: builder
    restart: always
    depends_on:
      - app
    expose:
      - "4200"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`cash-cockpit.local`)"
      - "traefik.http.routers.ui.entrypoints=web"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.ui.loadbalancer.server.port=4200"

networks:
  proxy:
    name: proxy_lan
    driver: bridge
  app-network:
    name: app_lan
    driver: bridge

volumes:
  postgres:
    name: cash_cockpit_db