version: '3.7'

services:
  ext_postgresql:
    container_name: ext_postgresql_v2
    image: postgres:12
    environment:
      POSTGRES_DB: cash_cockpit
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: verysecret
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    name: cash_cockpit_db